In [1]:
import numpy as np
import torch
import torch.optim as optim

C:\Users\mjsk1\anaconda3\envs\Pytorch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## simple linear regression

In [2]:
x_train= torch.FloatTensor([[1],[2],[3]])
y_train= torch.FloatTensor([[2],[4],[6]])

In [3]:
w=torch.zeros(1, requires_grad=True)
b= torch.zeros(1, requires_grad=True)

In [4]:
optimizer= optim.SGD([w,b],lr=0.01)
n_epochs=100
for epoch in range(1,n_epochs+1):
    hypothesis= x_train * w + b
    cost= torch.mean((hypothesis-y_train)**2)
    if epoch%10 ==0.:
        print('epoch {:4d} / {}, w: {:.3f}, cost: {:.6f}'.format(epoch, n_epochs, w.item(), cost.item()))
    optimizer.zero_grad() # 0으로 initialize
    cost.backward()  # backpropagation
    optimizer.step() # update
   

epoch   10 / 100, w: 1.101, cost: 2.313895
epoch   20 / 100, w: 1.511, cost: 0.284360
epoch   30 / 100, w: 1.642, cost: 0.088100
epoch   40 / 100, w: 1.688, cost: 0.066544
epoch   50 / 100, w: 1.707, cost: 0.061758
epoch   60 / 100, w: 1.717, cost: 0.058698
epoch   70 / 100, w: 1.725, cost: 0.055924
epoch   80 / 100, w: 1.732, cost: 0.053295
epoch   90 / 100, w: 1.738, cost: 0.050790
epoch  100 / 100, w: 1.744, cost: 0.048403


In [5]:
print(w,b)

tensor([1.7451], requires_grad=True) tensor([0.5795], requires_grad=True)


## Multivariable linear regression

In [6]:
x_train= torch.FloatTensor([[1,5,9],[2,4,7],[3,6,9]])
y_train= torch.FloatTensor([[22],[21],[30]])

In [7]:
w=torch.ones((3,1), requires_grad=True)
b= torch.zeros(1, requires_grad=True)
optimizer= optim.SGD([w,b],lr=1e-5)
n_epochs=1000
for epoch in range(1,n_epochs+1):
    hypothesis= x_train.matmul(w) + b
    cost= torch.mean((hypothesis-y_train)**2)
    if epoch%100 ==0.:
        print('epoch {:4d} / {}, cost: {:.6f}'.format(epoch, n_epochs, cost.item()))
    optimizer.zero_grad() # 0으로 initialize
    cost.backward()  # backpropagation
    optimizer.step() # update

epoch  100 / 1000, cost: 58.416199
epoch  200 / 1000, cost: 39.995365
epoch  300 / 1000, cost: 27.693430
epoch  400 / 1000, cost: 19.476860
epoch  500 / 1000, cost: 13.987984
epoch  600 / 1000, cost: 10.320362
epoch  700 / 1000, cost: 7.868727
epoch  800 / 1000, cost: 6.228994
epoch  900 / 1000, cost: 5.131334
epoch 1000 / 1000, cost: 4.395679


In [8]:
w,b

(tensor([[1.1842],
         [1.4021],
         [1.6446]], requires_grad=True),
 tensor([0.0771], requires_grad=True))

## use class 

In [9]:
import torch.nn.functional as F
import torch.nn as nn

In [10]:
x_train= torch.FloatTensor([[1,5,9],[2,4,7],[3,6,9]])
y_train= torch.FloatTensor([[22],[21],[30]])

In [11]:
class regressionmodel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear= nn.Linear(3,1)
    
    def forward(self,x):
        return self.linear(x)
model= regressionmodel()

optimizer=optim.SGD(model.parameters(),lr=1e-5)
n_epochs=1000
for epoch in range(1,n_epochs+1):
    hypothesis= model(x_train)
    cost=F.mse_loss( hypothesis,y_train)
   
    optimizer.zero_grad()
    cost.backward()  
    optimizer.step()
    
    if epoch%100 ==0.:
        print('epoch {:4d} / {}, cost: {:.6f}'.format(epoch, n_epochs, cost.item()))

epoch  100 / 1000, cost: 374.948395
epoch  200 / 1000, cost: 252.733276
epoch  300 / 1000, cost: 171.126419
epoch  400 / 1000, cost: 116.632484
epoch  500 / 1000, cost: 80.241417
epoch  600 / 1000, cost: 55.937130
epoch  700 / 1000, cost: 39.702885
epoch  800 / 1000, cost: 28.856842
epoch  900 / 1000, cost: 21.608467
epoch 1000 / 1000, cost: 16.762121


## Logistic Regression

In [83]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [84]:
torch.manual_seed(1)

In [85]:
x_data= [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data= [[0],[0],[0],[1],[1],[1]]

In [86]:
x_train= torch.FloatTensor(x_data)
y_train= torch.FloatTensor(y_data)

In [87]:
w= torch.zeros((2,1),requires_grad=True)
b= torch.zeros(1,requires_grad=True)

In [88]:
hypothesis1= 1 / (1+torch.exp(-(x_train.matmul(w) + b))) # sigmoid function
# torxh.matmul(x,w) 도 가능 
# torch.sigmoid() 제공
hypothesis= torch.sigmoid(x_train.matmul(w) + b)

In [89]:
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
torch.Size([6, 1])


In [90]:
losses= -(y_train * torch.log(hypothesis) + (1-y_train) * torch.log(1- hypothesis))
print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward0>)


In [91]:
cost=losses.mean()
cost

tensor(0.6931, grad_fn=<MeanBackward0>)

In [92]:
# 한번에 computing the cost function
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

In [93]:
# training
optimizer= optim.SGD([w,b], lr=1)
nb_epochs=1000
for epoch in range(nb_epochs + 1):
    hypothesis= torch.sigmoid(x_train.matmul(w) + b)
    cost= F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad() #
    cost.backward()
    optimizer.step()
    
    if epoch % 100 ==0:
        print('epoch {:4d}/{} cost: {:.6f}'.format(epoch,nb_epochs, cost.item()))

epoch    0/1000 cost: 0.693147
epoch  100/1000 cost: 0.134722
epoch  200/1000 cost: 0.080643
epoch  300/1000 cost: 0.057900
epoch  400/1000 cost: 0.045300
epoch  500/1000 cost: 0.037261
epoch  600/1000 cost: 0.031672
epoch  700/1000 cost: 0.027556
epoch  800/1000 cost: 0.024394
epoch  900/1000 cost: 0.021888
epoch 1000/1000 cost: 0.019852


In [53]:
hypothesis= torch.sigmoid(x_train.matmul(w) + b)
print(hypothesis)

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)


In [54]:
prediction= hypothesis>=torch.FloatTensor([0.5])
print(prediction)

tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


## using class

In [105]:
torch.manual_seed(1)
x_data= [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data= [[0],[0],[0],[1],[1],[1]]
x_train= torch.FloatTensor(x_data)
y_train= torch.FloatTensor(y_data)

class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.linear(x))


In [106]:
model = BinaryClassifier()
optimizer= optim.SGD(model.parameters(), lr=1)
nb_epochs=1000
for epoch in range(nb_epochs + 1):
    hypothesis= model(x_train)
    cost= F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad() #
    cost.backward()
    optimizer.step()
    
    if epoch % 100 ==0:
        print('epoch {:4d}/{} cost: {:.6f}'.format(epoch,nb_epochs, cost.item()))

epoch    0/1000 cost: 0.539713
epoch  100/1000 cost: 0.134272
epoch  200/1000 cost: 0.080486
epoch  300/1000 cost: 0.057820
epoch  400/1000 cost: 0.045251
epoch  500/1000 cost: 0.037228
epoch  600/1000 cost: 0.031649
epoch  700/1000 cost: 0.027538
epoch  800/1000 cost: 0.024381
epoch  900/1000 cost: 0.021877
epoch 1000/1000 cost: 0.019843


In [107]:
list(model.parameters())

[Parameter containing:
 tensor([[3.2534, 1.5181]], requires_grad=True),
 Parameter containing:
 tensor([-14.4839], requires_grad=True)]